export const studentList = [
  {
    name: "Ruth Solomon",
    github: "https://github.com/ruthless134/YotorFinal/",
    megaUrl: "https://ruthless134.github.io/YotorFinal/",
    linkedin: "https://www.linkedin.com",
    imgCertificate: "certificates_and_mega/ruth.png",
    certificate: "certificates_and_mega/ruth.pdf",
    index: "1",
    cv: "",
  },
  {
    name: "Yonas Ayele",
    github: "https://github.com/japuyon/",
    megaUrl: "https://japuyon.github.io/Mega-project/",
    linkedin: "https://www.linkedin.com/in/yonas-ayele-9b9123288",
    imgCertificate: "certificates_and_mega/yoni.png",
    certificate: "certificates_and_mega/yoni.pdf",
    index: "2",
    cv: "",
  },
  {
    name: "Yanet Dagne",
    github: "https://github.com/yanet-codes/",
    megaUrl:
      "https://yanet-codes.github.io/Nina/CSS%20mega-project%20copy.html",
    linkedin: "https://linkedin.com/in/yanet-dagne-amdetsion-92054b316",
    imgCertificate: "certificates_and_mega/yanet.png",
    certificate: "certificates_and_mega/yanet.pdf",
    index: "3",
    cv: "",
  },
  {
    name: "Meklit",
    github: "https://github.com/japuyon/",
    megaUrl:
      "https://yanet-codes.github.io/Nina/CSS%20mega-project%20copy.html",
    linkedin: "https://linkedin.com/in/yanet-dagne-amdetsion-92054b316",
    imgCertificate: "certificates_and_mega/ruth.png",
    certificate: "certificates_and_mega/all.pdf",
    index: "4",
    cv: "",
  },
  {
    name: "Betelhem Sintayehu",
    github: "https://github.com/betty-19/",
    megaUrl:
      "https://betty-19.github.io/Mega-Project/mega_project/mega_project.html",
    linkedin: "https://www.linkedin.com/in/betelhem-sintayehu-505901245",
    imgCertificate: "certificates_and_mega/ruth.png",
    certificate: "certificates_and_mega/all.pdf",
    index: "5",
    cv: "cv/beti_cv.pdf",
  },
];
